### ISSUE TITLE
[💡 Feature Request] Field Type "Group"

### ISSUE THREAD

**Issue by SuddenDev** [pruvious/pruvious#22]
Now, that I finally have time and a real project to sink my teeth into this CMS, I've come to my first little hurdle.

I think it would be nice to be able to group certain fields together visually and / or structurally.
Let's say that you have address fields that are in a single collection  (e.g. Settings). Currently all of the fields are visually each a full line of text, which makes editing more difficult. 
In the data, that you receive in the FE, it does not bother me so much, that I can't group multiple fields together, but it would be a nice touch.

I think a (visual)-group field would be nice and could work similarly to the layout feature of the repeater field. More finetuning of sizes (like a option to give a percentage of the column / row width)  would be extra awesome, but the former works just fine imo.

What are your opinion on this @murisceman ?
Or did I just not see that feature in the docs?

In any case, I'm still extremely happy i stumbled upon this project. Stellar work my friend!

I'll get back with more feedback if something comes up!
Cheers 🍻

**Comment by murisceman** [comment]
Hey, I'm glad to hear that you are enjoying working with it!

The good news is that field grouping is already available. There are many nice things that haven't been documented yet because I currently lack the time to write up more details and examples. However, here is what you're looking for: [https://github.com/pruvious/pruvious/blob/main/src/runtime/collections/collection.definition.ts#L122-L164](https://github.com/pruvious/pruvious/blob/main/src/runtime/collections/collection.definition.ts#L122-L164)

Additionally, here is an example of its usage: [https://pruvious.com/tutorial/03-header-and-footer#settings-collection](https://pruvious.com/tutorial/03-header-and-footer#settings-collection)

Cheers! 🍻

**Comment by SuddenDev** [comment]
Oh excellent! Yeah I did not know this existed or could be also used like this! I did see the tutorial example, but I thought you were just able to set tabs with it (which was already pretty neat).

Thank you for your swift answer! ❤️
