### ISSUE TITLE
getCollectionData in blocks possible?

### ISSUE THREAD

**Issue by SuddenDev** [pruvious/pruvious#24]
Sorry, for another question.

I've added a Single Collection (settings), as in the tutorial, and would like to display some information of that in a block. It seems the `getCollectionData` function from the docs is not meant to do that in blocks, since it breaks the dashboard and (sometimes) the client, although sometimes it works.

I was already considering writing a custom endpoint and using the query function to provide the settings collection to my block, but I wanted to check if there's a better way that might not be in the docs. Or maybe there's a good reason to why this does not really work.

Thanks again. 

---
#### Edit:
I just tested what happens if I wrap that element in it's own component and there it works fine as far as I can tell.

**Comment by murisceman** [comment]
Hi! No worries, if something is unclear, just drop a question here. This also helps feed search engines with useful information and issues related to Pruvious.

The `getCollectionData` utility should work in all Vue components. Have you placed it before `defineBlock` or `defineProps`? If so, that's the issue - all component logic should be positioned below those two macros. This is because Pruvious parses the block components and resolves related imports on the server side (allowing you to share field options across components). When code is placed before the macros, Pruvious won't strip it out, and since `getCollectionData` is client-only, the program crashes.
