### ISSUE TITLE
[💡 Feature Idea]: Allow pageLike collections without page building

### ISSUE THREAD

**Issue by SuddenDev** [pruvious/pruvious#26]
Hi @murisceman!

I was just working again on my project and I while building a custom collection with a page template I was thinking that it would be great if the collection "Page Like Collections" could be extended.

My current issue is, that while I don't need or want the Block Editor of the Page Collection, I need some or most of the other things (Slugs, SEO, maybe Draft/Publish and Preview). My reasoning for this is just that I want to create a template where the client fills out the config of said collection and then every page has the same structure.

My suggestion would the option to disable the `contentBuilder` also in `pageLikeCollection`. I think the only issue would be that the built in dynamic route would then not really work, but you could still easily get the content of the collection with `useAsyncData` and a vue template file in a dynamic page as before.

Am I missing something crucial why this is a bad idea? 
Or do you see an even easier option?

As always, thanks for your hard work! Let me know if I can help!

---
PS: Also thanks for continuing your tutorial. The "blog" section was pretty helpfull to see whats best practice.

**Comment by SuddenDev** [comment]
Okay, I figured a way out that already sort of works for me.
Basically, I just create a new `pageLikeCollection` as usual, set a specific layout and just get all the fields through the usePage composable like in the blog tutorial. Works like a charm for routing and so on.
At the moment, I just don't allow any blocks in the collection, which makes sure that the clients can not and don't have change the page structure.

But I do think the option to disable the page preview and / or the blocks sidebar (maybe even seperately) would be a great addition, since the fields in the right sidebar are a bit too narrow for a long form. I think even a CSS solution might do the trick.

Let me know what you think!

**Comment by murisceman** [comment]
Hey @SuddenDev!

This is totally possible, and the easiest way to do it is by using the `pageLikeCollection` to predefine the definition and then simply disable the `contentBuilder` option before exporting it via `defineCollection`. This option is not shown in the autocomplete currently because the `pageLikeCollection` utility returns an object of type `CollectionDefinition`, which is either a `SingleEntryCollectionDefinition` (_cannot have a content builder_) or `MultiEntryCollectionDefinition`. In commit 09e0b6861a34f38e211fee2412044b2feb629963, I have fixed this to always use `MultiEntryCollectionDefinition`, which is the more specific type.

This will be fixed in the next release, along with commits b4a37fbddb2bbbba452d04cddb49a251286a45ab and f2c0a00842beffa506ba87652b3ec641cb45c54a. Until then, you can do something like this:

```ts
import { defineCollection } from '#pruvious'
import { pageLikeCollection } from '#pruvious/standard'

const products = pageLikeCollection({
  name: 'products',
  pathPrefix: 'products',
}) as ReturnType<typeof pageLikeCollection> & { mode: 'multi' } // Now it's MultiEntryCollectionDefinition

products.contentBuilder = false

export default defineCollection(products)
```

You can adjust the definition options as you prefer from here on, such as the field layout and so forth. I intentionally did not include the `contentBuilder` option in the `pageLikeCollection` helper to maintain the simplicity of this utility. Since it merely returns an object without registering any collection, it remains highly extendable for more advanced uses like yours.

---

I'm pleased to hear that you enjoyed the new tutorial lesson! I'll aim to write up the "Contact form" during the upcoming weekend.

**Comment by SuddenDev** [comment]
Thank you very much for that! I should've thought of something like that as well I guess.
This works perfect already.

The only issue seems to be that the fieldsLayout breaks a bit (no tabs for Seo for example). But I'll just try to overwrite that.
Maybe this would be a good addition to the docs as well. If you want to, I can write a first draft of that doc.

**Comment by murisceman** [comment]
No problem!

Regarding the missing tabs, it's because special layout items are used for the edit page with the content builder. You can check here the defaults:

https://github.com/pruvious/pruvious/blob/f2c0a00842beffa506ba87652b3ec641cb45c54a/src/runtime/collections/page-like.ts#L142-L158

Items starting with `#` are displayed as special tabs (the ones used in the content builder sidebar) and they are not normal tabs. It should be possible to add custom special tabs, but they won't work on a normal edit page (without the content builder), so you definitely need to adjust this array to your needs for your case. Also, I figured out that I haven't documented this at all ^^'

Any help with improving the documentation is highly appreciated 🙏

**Comment by SuddenDev** [comment]
Just closing this, since my question was more answered.
