### ISSUE TITLE
Missing Pruvious Dashboard Translations

### ISSUE THREAD

**Issue by SuddenDev** [pruvious/pruvious#31]
Hey Muris!

I found another thing that came up. My current project is only in German, so I was faced with updating my languages in the nuxt.config.ts as described by the docs. (So that the correct `html lang="de"` is rendered.)
Everything in the frontend works well, but in the dashboard, Pruvious is looking for the german translated-strings file (which currently does not exist). So now I have a couple of $item and $page springled in the dashboard. (See image attached).

<img width="1512" alt="image" src="https://github.com/pruvious/pruvious/assets/22402545/f31049e7-063a-4e9c-a649-b2048169c6bf">

I don't think this is a big issue for me at the moment, but I was thinking that it would be nice if pruvious had some translations for the dashboard in a couple of languages out of the box. I do only speak German and English (as do you afaik 😄 ), but I'd be happy to translate the default dashboard file to German with a PR. Maybe someone else would like to do other langs and so on too.
Should I create one in `src/runtime/translatable-strings/standard/` ?

I the meantime, I think it would also be a good addition if English would be displayed if the other translated strings don't exist (which already kinda works, but breaks with variables as it seems).

Anyway, let me know what you think! 

Cheers!

---
PS: Da du auch aus München bist (glaub ich), würd ich dir gern mal ein Bier ausgeben für die ganze harte Arbeit. Entweder so oder über BuyMeACoffee oder so 😃

**Comment by murisceman** [comment]
Hey Dominik!

This should be fixed now in [v3.11.7](https://github.com/pruvious/pruvious/releases/tag/v3.11.7). I added a definitive fallback in English for the translatable strings API route. Before that, the fallback was the primary language (in your case DE), which is why you received a 404 error when trying to fetch the translatable strings (the dashboard strings are only available in English at the moment). The 'Search $items' and 'Add $item' are just string patterns that are displayed as fallback strings in Vue components.

Regarding dashboard translations in general - I've prepared this feature from the start, but never found the time to fully implement and test it. Users already have a hidden field called `dashboardLanguage`:

https://github.com/pruvious/pruvious/blob/25a83aeeceb2ca879307ba4f4a7b3334a6bf0e9f/src/runtime/collections/standard/users.collection.ts#L314-L332

---

Gerne können wir uns zu einem Bier treffen! Schreib mir über Discord, wann es dir passt :)
