### ISSUE TITLE
Idea: Custom fields

### ISSUE THREAD

**Issue by vanling** [pruvious/pruvious#78]
I know this will be a stretch for now, but are custom fields already possible somehow? 

Current usecases for me:
**- a colorPicker**
--- for now i can just add manual hex codes
**- an image (naming things is hard) location annotator** (example below)
-- Right now im just using an Image + repeater with (text, link, topPos,leftPos)

This works for developers, but when this is done it will be in the hands of (no offence) "simple" marketeers x') 
<img width="840" alt="Screenshot 2024-11-07 at 17 26 08" src="https://github.com/user-attachments/assets/b3413c78-b5ae-4178-95c6-5ed00f0506f0">

Would love to make some magic interface when you can select a position on the image with the mouse.

**Comment by vanling** [comment]
👀  Just seen the `additionalRecordOptionsVueComponent` on a multi-collection 👀 
This might help me with creating something for the annotations

**Comment by murisceman** [comment]
Yes, custom fields are possible, but they are not documented because I am not satisfied with the DX regarding Vue components. However, you can create one by adding a TypeScript file in the `fields` directory of your project:

```ts
import { defineField } from "#pruvious";

export default defineField({
  // ...
})
```

Here is an example of a simple field definition: https://github.com/pruvious/pruvious/blob/main/src/runtime/fields/standard/switch.field.ts

You can find comments and examples in the code; see here: https://github.com/pruvious/pruvious/blob/a9221fbe3a73daa590c8c062dafce6b4d5978c53/src/runtime/fields/field.definition.ts

**Comment by vanling** [comment]
Thanks for the help :)
